export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCT_BYID_REQUEST = 'GET_PRODUCT_BYID_REQUEST';
export const GET_PRODUCT_BYID_SUCCESS = 'GET_PRODUCT_BYID_SUCCESS';
export const GET_PRODUCT_BYID_FAIL = 'GET_PRODUCT_BYID_FAIL';

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAIL = 'DELETE_TODO_FAIL';

export const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
export const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
export const EDIT_TODO_FAIL = 'EDIT_TODO_FAIL';
export const EDIT_TODO_RESET = 'EDIT_TODO_RESET';

export const TODO_CREATE_REQUEST = 'TODO_CREATE_REQUEST';
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS';
export const TODO_CREATE_FAIL = 'TODO_CREATE_FAIL';
export const TODO_CREATE_RESET = 'TODO_CREATE_RESET';
